default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000
  username: username
  password: password

development:
  <<: *default
  database: homemade_development

test:
  <<: *default
  database: homemade_test

production:
  <<: *default
  database: postgresql
